import { CaddieGroupManagement, GroupFilterOption } from "../types";

// 드롭다운 옵션들
export const GROUP_OPTIONS: GroupFilterOption[] = [
  { value: "전체", label: "그룹" },
  { value: "1조", label: "1조" },
  { value: "2조", label: "2조" },
  { value: "3조", label: "3조" },
  { value: "4조", label: "4조" },
  { value: "5조", label: "5조" },
  { value: "6조", label: "6조" },
  { value: "7조", label: "7조" },
  { value: "8조", label: "8조" },
  { value: "9조", label: "9조" },
];

export const SPECIAL_TEAM_OPTIONS: GroupFilterOption[] = [
  { value: "전체", label: "특수반" },
  { value: "새싹", label: "새싹캐디" },
  { value: "1-2부반", label: "1-2부반" },
  { value: "2-3부반", label: "2-3부반" },
  { value: "2부반", label: "2부반" },
];

export const STATUS_OPTIONS: GroupFilterOption[] = [
  { value: "전체", label: "상태" },
  { value: "근무", label: "근무" },
  { value: "당번", label: "당번" },
  { value: "휴무", label: "휴무" },
];

// 모크 데이터
export const MOCK_GROUPS_DATA: CaddieGroupManagement[] = [
  {
    id: "group-1",
    name: "1조",
    memberCount: 25,
    caddies: [
      {
        id: 1,
        name: "홍길동",
        group: 1,
        badge: "하우스",
        status: "근무",
        specialBadge: "조첫",
      },
      {
        id: 2,
        name: "김철수",
        group: 1,
        badge: "하우스",
        status: "근무",
        specialBadge: "부조장",
      },
      { id: 3, name: "이영희", group: 1, badge: "하우스", status: "근무" },
      { id: 4, name: "박민수", group: 1, badge: "하우스", status: "근무" },
      {
        id: 5,
        name: "최수정",
        group: 1,
        badge: "2-3부반",
        status: "당번",
        specialBadge: "조첫",
      },
      { id: 6, name: "정태영", group: 1, badge: "하우스", status: "근무" },
      { id: 7, name: "이미영", group: 1, badge: "2-3부반", status: "당번" },
      { id: 8, name: "김민지", group: 1, badge: "하우스", status: "근무" },
      { id: 9, name: "황진우", group: 1, badge: "2부반", status: "당번" },
      { id: 10, name: "손예진", group: 1, badge: "하우스", status: "근무" },
      { id: 11, name: "배수지", group: 1, badge: "하우스", status: "근무" },
      { id: 12, name: "김유진", group: 1, badge: "2부반", status: "당번" },
      { id: 13, name: "이서연", group: 1, badge: "하우스", status: "근무" },
      { id: 14, name: "박지영", group: 1, badge: "하우스", status: "근무" },
      { id: 15, name: "최하늘", group: 1, badge: "하우스", status: "근무" },
      { id: 16, name: "정민호", group: 1, badge: "2부반", status: "당번" },
      { id: 17, name: "김태현", group: 1, badge: "하우스", status: "근무" },
      { id: 18, name: "이준석", group: 1, badge: "하우스", status: "근무" },
      { id: 19, name: "박소영", group: 1, badge: "하우스", status: "근무" },
      { id: 20, name: "최민석", group: 1, badge: "하우스", status: "근무" },
      { id: 21, name: "정유나", group: 1, badge: "하우스", status: "근무" },
      { id: 22, name: "김승호", group: 1, badge: "하우스", status: "근무" },
      { id: 23, name: "이다은", group: 1, badge: "하우스", status: "근무" },
      { id: 24, name: "박준혁", group: 1, badge: "하우스", status: "근무" },
      { id: 25, name: "최아름", group: 1, badge: "하우스", status: "근무" },
    ],
  },
  {
    id: "group-2",
    name: "2조",
    memberCount: 20,
    caddies: [
      {
        id: 26,
        name: "강민수",
        group: 2,
        badge: "하우스",
        status: "근무",
        specialBadge: "조첫",
      },
      {
        id: 27,
        name: "송지현",
        group: 2,
        badge: "하우스",
        status: "근무",
        specialBadge: "부조장",
      },
      { id: 28, name: "윤서준", group: 2, badge: "하우스", status: "근무" },
      { id: 29, name: "한예슬", group: 2, badge: "새싹", status: "근무" },
      { id: 30, name: "오민재", group: 2, badge: "하우스", status: "근무" },
      { id: 31, name: "류현진", group: 2, badge: "하우스", status: "근무" },
      { id: 32, name: "김나영", group: 2, badge: "1-2부반", status: "근무" },
      { id: 33, name: "박서준", group: 2, badge: "하우스", status: "근무" },
      { id: 34, name: "이수현", group: 2, badge: "하우스", status: "휴무" },
      { id: 35, name: "최민영", group: 2, badge: "하우스", status: "근무" },
      { id: 36, name: "정우성", group: 2, badge: "하우스", status: "근무" },
      { id: 37, name: "김하늘", group: 2, badge: "하우스", status: "근무" },
      { id: 38, name: "이태민", group: 2, badge: "하우스", status: "근무" },
      { id: 39, name: "박지수", group: 2, badge: "하우스", status: "근무" },
      { id: 40, name: "최윤서", group: 2, badge: "하우스", status: "근무" },
      { id: 41, name: "정민수", group: 2, badge: "하우스", status: "근무" },
      { id: 42, name: "김예진", group: 2, badge: "하우스", status: "근무" },
      { id: 43, name: "이동혁", group: 2, badge: "하우스", status: "근무" },
      { id: 44, name: "박민지", group: 2, badge: "하우스", status: "근무" },
      { id: 45, name: "최준호", group: 2, badge: "하우스", status: "근무" },
    ],
  },
  {
    id: "group-3",
    name: "3조",
    memberCount: 18,
    caddies: [
      {
        id: 46,
        name: "임현우",
        group: 3,
        badge: "하우스",
        status: "근무",
        specialBadge: "조첫",
      },
      {
        id: 47,
        name: "조미래",
        group: 3,
        badge: "하우스",
        status: "근무",
        specialBadge: "부조장",
      },
      { id: 48, name: "신동욱", group: 3, badge: "하우스", status: "근무" },
      { id: 49, name: "한소희", group: 3, badge: "새싹", status: "근무" },
      { id: 50, name: "김도현", group: 3, badge: "하우스", status: "근무" },
      { id: 51, name: "이채영", group: 3, badge: "하우스", status: "근무" },
      { id: 52, name: "박성훈", group: 3, badge: "하우스", status: "근무" },
      { id: 53, name: "최예은", group: 3, badge: "1-2부반", status: "근무" },
      { id: 54, name: "정재현", group: 3, badge: "하우스", status: "근무" },
      { id: 55, name: "김서연", group: 3, badge: "하우스", status: "근무" },
      { id: 56, name: "이준영", group: 3, badge: "하우스", status: "당번" },
      { id: 57, name: "박유진", group: 3, badge: "하우스", status: "근무" },
      { id: 58, name: "최건우", group: 3, badge: "하우스", status: "근무" },
      { id: 59, name: "정다은", group: 3, badge: "하우스", status: "근무" },
      { id: 60, name: "김민재", group: 3, badge: "하우스", status: "근무" },
      { id: 61, name: "이소영", group: 3, badge: "하우스", status: "근무" },
      { id: 62, name: "박태준", group: 3, badge: "하우스", status: "근무" },
      { id: 63, name: "최하윤", group: 3, badge: "하우스", status: "근무" },
    ],
  },
  {
    id: "group-4",
    name: "4조",
    memberCount: 22,
    caddies: [
      {
        id: 64,
        name: "문재인",
        group: 4,
        badge: "하우스",
        status: "근무",
        specialBadge: "조첫",
      },
      {
        id: 65,
        name: "안유진",
        group: 4,
        badge: "하우스",
        status: "근무",
        specialBadge: "부조장",
      },
      { id: 66, name: "서강준", group: 4, badge: "하우스", status: "근무" },
      { id: 67, name: "김지원", group: 4, badge: "2-3부반", status: "당번" },
      { id: 68, name: "이도현", group: 4, badge: "하우스", status: "근무" },
      { id: 69, name: "박보영", group: 4, badge: "하우스", status: "근무" },
      { id: 70, name: "최우식", group: 4, badge: "하우스", status: "근무" },
      { id: 71, name: "정유미", group: 4, badge: "하우스", status: "근무" },
      { id: 72, name: "김선호", group: 4, badge: "하우스", status: "근무" },
      { id: 73, name: "이혜리", group: 4, badge: "새싹", status: "근무" },
      { id: 74, name: "박서함", group: 4, badge: "하우스", status: "근무" },
      { id: 75, name: "최민식", group: 4, badge: "하우스", status: "근무" },
      { id: 76, name: "정해인", group: 4, badge: "하우스", status: "근무" },
      { id: 77, name: "김고은", group: 4, badge: "하우스", status: "근무" },
      { id: 78, name: "이종석", group: 4, badge: "하우스", status: "휴무" },
      { id: 79, name: "박신혜", group: 4, badge: "하우스", status: "근무" },
      { id: 80, name: "최강창민", group: 4, badge: "하우스", status: "근무" },
      { id: 81, name: "정소민", group: 4, badge: "하우스", status: "근무" },
      { id: 82, name: "김남길", group: 4, badge: "하우스", status: "근무" },
      { id: 83, name: "이나영", group: 4, badge: "하우스", status: "근무" },
      { id: 84, name: "박혁권", group: 4, badge: "하우스", status: "근무" },
      { id: 85, name: "최수영", group: 4, badge: "하우스", status: "근무" },
    ],
  },
  {
    id: "group-5",
    name: "5조",
    memberCount: 19,
    caddies: [
      {
        id: 86,
        name: "송중기",
        group: 5,
        badge: "하우스",
        status: "근무",
        specialBadge: "조첫",
      },
      {
        id: 87,
        name: "김태희",
        group: 5,
        badge: "하우스",
        status: "근무",
        specialBadge: "부조장",
      },
      { id: 88, name: "이병헌", group: 5, badge: "하우스", status: "근무" },
      { id: 89, name: "전지현", group: 5, badge: "1-2부반", status: "근무" },
      { id: 90, name: "현빈", group: 5, badge: "하우스", status: "근무" },
      { id: 91, name: "손예진", group: 5, badge: "하우스", status: "근무" },
      { id: 92, name: "공유", group: 5, badge: "하우스", status: "당번" },
      { id: 93, name: "김고은", group: 5, badge: "하우스", status: "근무" },
      { id: 94, name: "이민호", group: 5, badge: "하우스", status: "근무" },
      { id: 95, name: "박민영", group: 5, badge: "새싹", status: "근무" },
      { id: 96, name: "조인성", group: 5, badge: "하우스", status: "근무" },
      { id: 97, name: "한지민", group: 5, badge: "하우스", status: "근무" },
      { id: 98, name: "강동원", group: 5, badge: "하우스", status: "근무" },
      { id: 99, name: "이영애", group: 5, badge: "하우스", status: "근무" },
      { id: 100, name: "원빈", group: 5, badge: "하우스", status: "휴무" },
      { id: 101, name: "김희선", group: 5, badge: "하우스", status: "근무" },
      { id: 102, name: "장동건", group: 5, badge: "하우스", status: "근무" },
      { id: 103, name: "고소영", group: 5, badge: "하우스", status: "근무" },
      { id: 104, name: "유아인", group: 5, badge: "하우스", status: "근무" },
    ],
  },
  {
    id: "group-6",
    name: "6조",
    memberCount: 21,
    caddies: [
      {
        id: 105,
        name: "박보검",
        group: 6,
        badge: "하우스",
        status: "근무",
        specialBadge: "조첫",
      },
      {
        id: 106,
        name: "수지",
        group: 6,
        badge: "하우스",
        status: "근무",
        specialBadge: "부조장",
      },
      { id: 107, name: "박서준", group: 6, badge: "하우스", status: "근무" },
      { id: 108, name: "아이유", group: 6, badge: "2부반", status: "당번" },
      { id: 109, name: "이승기", group: 6, badge: "하우스", status: "근무" },
      { id: 110, name: "유인나", group: 6, badge: "하우스", status: "근무" },
      { id: 111, name: "김우빈", group: 6, badge: "하우스", status: "근무" },
      { id: 112, name: "한효주", group: 6, badge: "하우스", status: "근무" },
      { id: 113, name: "조정석", group: 6, badge: "하우스", status: "근무" },
      { id: 114, name: "정유미", group: 6, badge: "2-3부반", status: "근무" },
      { id: 115, name: "남주혁", group: 6, badge: "하우스", status: "근무" },
      { id: 116, name: "김지원", group: 6, badge: "하우스", status: "근무" },
      { id: 117, name: "윤계상", group: 6, badge: "하우스", status: "근무" },
      { id: 118, name: "한가인", group: 6, badge: "하우스", status: "근무" },
      { id: 119, name: "이제훈", group: 6, badge: "하우스", status: "휴무" },
      { id: 120, name: "신민아", group: 6, badge: "하우스", status: "근무" },
      { id: 121, name: "김수현", group: 6, badge: "하우스", status: "근무" },
      { id: 122, name: "전도연", group: 6, badge: "하우스", status: "근무" },
      { id: 123, name: "하정우", group: 6, badge: "하우스", status: "근무" },
      { id: 124, name: "김혜수", group: 6, badge: "하우스", status: "근무" },
      { id: 125, name: "조승우", group: 6, badge: "하우스", status: "근무" },
    ],
  },
  {
    id: "group-7",
    name: "7조",
    memberCount: 17,
    caddies: [
      {
        id: 126,
        name: "이정재",
        group: 7,
        badge: "하우스",
        status: "근무",
        specialBadge: "조첫",
      },
      {
        id: 127,
        name: "김희애",
        group: 7,
        badge: "하우스",
        status: "근무",
        specialBadge: "부조장",
      },
      { id: 128, name: "황정민", group: 7, badge: "하우스", status: "근무" },
      { id: 129, name: "고현정", group: 7, badge: "새싹", status: "근무" },
      { id: 130, name: "설경구", group: 7, badge: "하우스", status: "근무" },
      { id: 131, name: "염정아", group: 7, badge: "하우스", status: "근무" },
      { id: 132, name: "이병헌", group: 7, badge: "하우스", status: "당번" },
      { id: 133, name: "김여진", group: 7, badge: "하우스", status: "근무" },
      { id: 134, name: "최민식", group: 7, badge: "하우스", status: "근무" },
      { id: 135, name: "문소리", group: 7, badge: "1-2부반", status: "근무" },
      { id: 136, name: "송강호", group: 7, badge: "하우스", status: "근무" },
      { id: 137, name: "전도연", group: 7, badge: "하우스", status: "근무" },
      { id: 138, name: "류승범", group: 7, badge: "하우스", status: "근무" },
      { id: 139, name: "배두나", group: 7, badge: "하우스", status: "근무" },
      { id: 140, name: "마동석", group: 7, badge: "하우스", status: "휴무" },
      { id: 141, name: "김혜수", group: 7, badge: "하우스", status: "근무" },
      { id: 142, name: "박해일", group: 7, badge: "하우스", status: "근무" },
    ],
  },
  {
    id: "group-8",
    name: "8조",
    memberCount: 23,
    caddies: [
      {
        id: 143,
        name: "유해진",
        group: 8,
        badge: "하우스",
        status: "근무",
        specialBadge: "조첫",
      },
      {
        id: 144,
        name: "김옥빈",
        group: 8,
        badge: "하우스",
        status: "근무",
        specialBadge: "부조장",
      },
      { id: 145, name: "정우성", group: 8, badge: "하우스", status: "근무" },
      { id: 146, name: "한지민", group: 8, badge: "2부반", status: "당번" },
      { id: 147, name: "이성민", group: 8, badge: "하우스", status: "근무" },
      { id: 148, name: "김하늘", group: 8, badge: "하우스", status: "근무" },
      { id: 149, name: "조진웅", group: 8, badge: "하우스", status: "근무" },
      { id: 150, name: "이영애", group: 8, badge: "하우스", status: "근무" },
      { id: 151, name: "김윤석", group: 8, badge: "하우스", status: "근무" },
      { id: 152, name: "손예진", group: 8, badge: "2-3부반", status: "근무" },
      { id: 153, name: "이선균", group: 8, badge: "하우스", status: "근무" },
      { id: 154, name: "김태리", group: 8, badge: "하우스", status: "근무" },
      { id: 155, name: "박해수", group: 8, badge: "하우스", status: "근무" },
      { id: 156, name: "전여빈", group: 8, badge: "하우스", status: "근무" },
      { id: 157, name: "이제훈", group: 8, badge: "하우스", status: "휴무" },
      { id: 158, name: "김다미", group: 8, badge: "하우스", status: "근무" },
      { id: 159, name: "유연석", group: 8, badge: "하우스", status: "근무" },
      { id: 160, name: "박소담", group: 8, badge: "하우스", status: "근무" },
      { id: 161, name: "최우식", group: 8, badge: "하우스", status: "근무" },
      { id: 162, name: "김혜윤", group: 8, badge: "하우스", status: "근무" },
      { id: 163, name: "안재홍", group: 8, badge: "하우스", status: "근무" },
      { id: 164, name: "박주현", group: 8, badge: "하우스", status: "근무" },
      { id: 165, name: "윤여정", group: 8, badge: "하우스", status: "근무" },
    ],
  },
  {
    id: "group-9",
    name: "9조",
    memberCount: 20,
    caddies: [
      {
        id: 166,
        name: "이동휘",
        group: 9,
        badge: "하우스",
        status: "근무",
        specialBadge: "조첫",
      },
      {
        id: 167,
        name: "정유미",
        group: 9,
        badge: "하우스",
        status: "근무",
        specialBadge: "부조장",
      },
      { id: 168, name: "공명", group: 9, badge: "하우스", status: "근무" },
      { id: 169, name: "김세정", group: 9, badge: "새싹", status: "근무" },
      { id: 170, name: "이광수", group: 9, badge: "하우스", status: "근무" },
      { id: 171, name: "송지효", group: 9, badge: "하우스", status: "근무" },
      { id: 172, name: "김종국", group: 9, badge: "하우스", status: "당번" },
      { id: 173, name: "전소민", group: 9, badge: "하우스", status: "근무" },
      { id: 174, name: "하하", group: 9, badge: "하우스", status: "근무" },
      { id: 175, name: "지석진", group: 9, badge: "1-2부반", status: "근무" },
      { id: 176, name: "양세찬", group: 9, badge: "하우스", status: "근무" },
      { id: 177, name: "송중기", group: 9, badge: "하우스", status: "근무" },
      { id: 178, name: "이요원", group: 9, badge: "하우스", status: "근무" },
      { id: 179, name: "김민준", group: 9, badge: "하우스", status: "근무" },
      { id: 180, name: "한소희", group: 9, badge: "하우스", status: "휴무" },
      { id: 181, name: "변우석", group: 9, badge: "하우스", status: "근무" },
      { id: 182, name: "김혜윤", group: 9, badge: "하우스", status: "근무" },
      { id: 183, name: "로운", group: 9, badge: "하우스", status: "근무" },
      { id: 184, name: "정채연", group: 9, badge: "하우스", status: "근무" },
      { id: 185, name: "장기용", group: 9, badge: "하우스", status: "근무" },
    ],
  },
];
